// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoke_token.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const setRevoke = `-- name: SetRevoke :exec
UPDATE refresh_tokens 
SET revoked_at = $1, updated_at = $2
WHERE token = $3
`

type SetRevokeParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) SetRevoke(ctx context.Context, arg SetRevokeParams) error {
	_, err := q.db.ExecContext(ctx, setRevoke, arg.RevokedAt, arg.UpdatedAt, arg.Token)
	return err
}
