// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET email = $1, hashed_password = $2
WHERE id = $3
`

type UpdatePasswordParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
